export enum GoalType {
  WEIGHT_LOSS = 'WEIGHT_LOSS',
  WEIGHT_GAIN = 'WEIGHT_GAIN',
  MUSCLE_GAIN = 'MUSCLE_GAIN',
  STEPS = 'STEPS',
  WATER_INTAKE = 'WATER_INTAKE',
  SLEEP = 'SLEEP',
  WORKOUTS = 'WORKOUTS',
  BODY_FAT = 'BODY_FAT',
  CUSTOM = 'CUSTOM',
}

export enum GoalStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}
